// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "extrusion-quality-system/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// TokenManagerMock is an autogenerated mock type for the TokenManager type
type TokenManagerMock struct {
	mock.Mock
}

type TokenManagerMock_Expecter struct {
	mock *mock.Mock
}

func (_m *TokenManagerMock) EXPECT() *TokenManagerMock_Expecter {
	return &TokenManagerMock_Expecter{mock: &_m.Mock}
}

// Generate provides a mock function with given fields: user
func (_m *TokenManagerMock) Generate(user domain.User) (string, error) {
	ret := _m.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(domain.User) (string, error)); ok {
		return rf(user)
	}
	if rf, ok := ret.Get(0).(func(domain.User) string); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(domain.User) error); ok {
		r1 = rf(user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TokenManagerMock_Generate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Generate'
type TokenManagerMock_Generate_Call struct {
	*mock.Call
}

// Generate is a helper method to define mock.On call
//   - user domain.User
func (_e *TokenManagerMock_Expecter) Generate(user interface{}) *TokenManagerMock_Generate_Call {
	return &TokenManagerMock_Generate_Call{Call: _e.mock.On("Generate", user)}
}

func (_c *TokenManagerMock_Generate_Call) Run(run func(user domain.User)) *TokenManagerMock_Generate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(domain.User))
	})
	return _c
}

func (_c *TokenManagerMock_Generate_Call) Return(_a0 string, _a1 error) *TokenManagerMock_Generate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TokenManagerMock_Generate_Call) RunAndReturn(run func(domain.User) (string, error)) *TokenManagerMock_Generate_Call {
	_c.Call.Return(run)
	return _c
}

// Parse provides a mock function with given fields: rawToken
func (_m *TokenManagerMock) Parse(rawToken string) (domain.AuthClaims, error) {
	ret := _m.Called(rawToken)

	if len(ret) == 0 {
		panic("no return value specified for Parse")
	}

	var r0 domain.AuthClaims
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (domain.AuthClaims, error)); ok {
		return rf(rawToken)
	}
	if rf, ok := ret.Get(0).(func(string) domain.AuthClaims); ok {
		r0 = rf(rawToken)
	} else {
		r0 = ret.Get(0).(domain.AuthClaims)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(rawToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TokenManagerMock_Parse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Parse'
type TokenManagerMock_Parse_Call struct {
	*mock.Call
}

// Parse is a helper method to define mock.On call
//   - rawToken string
func (_e *TokenManagerMock_Expecter) Parse(rawToken interface{}) *TokenManagerMock_Parse_Call {
	return &TokenManagerMock_Parse_Call{Call: _e.mock.On("Parse", rawToken)}
}

func (_c *TokenManagerMock_Parse_Call) Run(run func(rawToken string)) *TokenManagerMock_Parse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *TokenManagerMock_Parse_Call) Return(_a0 domain.AuthClaims, _a1 error) *TokenManagerMock_Parse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TokenManagerMock_Parse_Call) RunAndReturn(run func(string) (domain.AuthClaims, error)) *TokenManagerMock_Parse_Call {
	_c.Call.Return(run)
	return _c
}

// NewTokenManagerMock creates a new instance of TokenManagerMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenManagerMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenManagerMock {
	mock := &TokenManagerMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
