// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "extrusion-quality-system/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// UserRepositoryMock is an autogenerated mock type for the UserRepository type
type UserRepositoryMock struct {
	mock.Mock
}

type UserRepositoryMock_Expecter struct {
	mock *mock.Mock
}

func (_m *UserRepositoryMock) EXPECT() *UserRepositoryMock_Expecter {
	return &UserRepositoryMock_Expecter{mock: &_m.Mock}
}

// All provides a mock function with given fields: ctx
func (_m *UserRepositoryMock) All(ctx context.Context) ([]domain.User, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for All")
	}

	var r0 []domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.User, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.User); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepositoryMock_All_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'All'
type UserRepositoryMock_All_Call struct {
	*mock.Call
}

// All is a helper method to define mock.On call
//   - ctx context.Context
func (_e *UserRepositoryMock_Expecter) All(ctx interface{}) *UserRepositoryMock_All_Call {
	return &UserRepositoryMock_All_Call{Call: _e.mock.On("All", ctx)}
}

func (_c *UserRepositoryMock_All_Call) Run(run func(ctx context.Context)) *UserRepositoryMock_All_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *UserRepositoryMock_All_Call) Return(_a0 []domain.User, _a1 error) *UserRepositoryMock_All_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepositoryMock_All_Call) RunAndReturn(run func(context.Context) ([]domain.User, error)) *UserRepositoryMock_All_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, user
func (_m *UserRepositoryMock) Create(ctx context.Context, user domain.User) (domain.User, error) {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.User) (domain.User, error)); ok {
		return rf(ctx, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.User) domain.User); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Get(0).(domain.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.User) error); ok {
		r1 = rf(ctx, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepositoryMock_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type UserRepositoryMock_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - user domain.User
func (_e *UserRepositoryMock_Expecter) Create(ctx interface{}, user interface{}) *UserRepositoryMock_Create_Call {
	return &UserRepositoryMock_Create_Call{Call: _e.mock.On("Create", ctx, user)}
}

func (_c *UserRepositoryMock_Create_Call) Run(run func(ctx context.Context, user domain.User)) *UserRepositoryMock_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.User))
	})
	return _c
}

func (_c *UserRepositoryMock_Create_Call) Return(_a0 domain.User, _a1 error) *UserRepositoryMock_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepositoryMock_Create_Call) RunAndReturn(run func(context.Context, domain.User) (domain.User, error)) *UserRepositoryMock_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *UserRepositoryMock) FindByID(ctx context.Context, id domain.UserID) (domain.User, bool, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 domain.User
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.UserID) (domain.User, bool, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.UserID) domain.User); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.UserID) bool); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, domain.UserID) error); ok {
		r2 = rf(ctx, id)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// UserRepositoryMock_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type UserRepositoryMock_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.UserID
func (_e *UserRepositoryMock_Expecter) FindByID(ctx interface{}, id interface{}) *UserRepositoryMock_FindByID_Call {
	return &UserRepositoryMock_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *UserRepositoryMock_FindByID_Call) Run(run func(ctx context.Context, id domain.UserID)) *UserRepositoryMock_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.UserID))
	})
	return _c
}

func (_c *UserRepositoryMock_FindByID_Call) Return(_a0 domain.User, _a1 bool, _a2 error) *UserRepositoryMock_FindByID_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *UserRepositoryMock_FindByID_Call) RunAndReturn(run func(context.Context, domain.UserID) (domain.User, bool, error)) *UserRepositoryMock_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByUsername provides a mock function with given fields: ctx, username
func (_m *UserRepositoryMock) FindByUsername(ctx context.Context, username string) (domain.User, bool, error) {
	ret := _m.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for FindByUsername")
	}

	var r0 domain.User
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.User, bool, error)); ok {
		return rf(ctx, username)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.User); ok {
		r0 = rf(ctx, username)
	} else {
		r0 = ret.Get(0).(domain.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) bool); ok {
		r1 = rf(ctx, username)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, username)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// UserRepositoryMock_FindByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUsername'
type UserRepositoryMock_FindByUsername_Call struct {
	*mock.Call
}

// FindByUsername is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *UserRepositoryMock_Expecter) FindByUsername(ctx interface{}, username interface{}) *UserRepositoryMock_FindByUsername_Call {
	return &UserRepositoryMock_FindByUsername_Call{Call: _e.mock.On("FindByUsername", ctx, username)}
}

func (_c *UserRepositoryMock_FindByUsername_Call) Run(run func(ctx context.Context, username string)) *UserRepositoryMock_FindByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *UserRepositoryMock_FindByUsername_Call) Return(_a0 domain.User, _a1 bool, _a2 error) *UserRepositoryMock_FindByUsername_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *UserRepositoryMock_FindByUsername_Call) RunAndReturn(run func(context.Context, string) (domain.User, bool, error)) *UserRepositoryMock_FindByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// SetActive provides a mock function with given fields: ctx, id, isActive
func (_m *UserRepositoryMock) SetActive(ctx context.Context, id domain.UserID, isActive bool) (domain.User, bool, error) {
	ret := _m.Called(ctx, id, isActive)

	if len(ret) == 0 {
		panic("no return value specified for SetActive")
	}

	var r0 domain.User
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.UserID, bool) (domain.User, bool, error)); ok {
		return rf(ctx, id, isActive)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.UserID, bool) domain.User); ok {
		r0 = rf(ctx, id, isActive)
	} else {
		r0 = ret.Get(0).(domain.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.UserID, bool) bool); ok {
		r1 = rf(ctx, id, isActive)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, domain.UserID, bool) error); ok {
		r2 = rf(ctx, id, isActive)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// UserRepositoryMock_SetActive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetActive'
type UserRepositoryMock_SetActive_Call struct {
	*mock.Call
}

// SetActive is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.UserID
//   - isActive bool
func (_e *UserRepositoryMock_Expecter) SetActive(ctx interface{}, id interface{}, isActive interface{}) *UserRepositoryMock_SetActive_Call {
	return &UserRepositoryMock_SetActive_Call{Call: _e.mock.On("SetActive", ctx, id, isActive)}
}

func (_c *UserRepositoryMock_SetActive_Call) Run(run func(ctx context.Context, id domain.UserID, isActive bool)) *UserRepositoryMock_SetActive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.UserID), args[2].(bool))
	})
	return _c
}

func (_c *UserRepositoryMock_SetActive_Call) Return(_a0 domain.User, _a1 bool, _a2 error) *UserRepositoryMock_SetActive_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *UserRepositoryMock_SetActive_Call) RunAndReturn(run func(context.Context, domain.UserID, bool) (domain.User, bool, error)) *UserRepositoryMock_SetActive_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePassword provides a mock function with given fields: ctx, id, passwordHash
func (_m *UserRepositoryMock) UpdatePassword(ctx context.Context, id domain.UserID, passwordHash string) (domain.User, bool, error) {
	ret := _m.Called(ctx, id, passwordHash)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePassword")
	}

	var r0 domain.User
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.UserID, string) (domain.User, bool, error)); ok {
		return rf(ctx, id, passwordHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.UserID, string) domain.User); ok {
		r0 = rf(ctx, id, passwordHash)
	} else {
		r0 = ret.Get(0).(domain.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.UserID, string) bool); ok {
		r1 = rf(ctx, id, passwordHash)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, domain.UserID, string) error); ok {
		r2 = rf(ctx, id, passwordHash)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// UserRepositoryMock_UpdatePassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePassword'
type UserRepositoryMock_UpdatePassword_Call struct {
	*mock.Call
}

// UpdatePassword is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.UserID
//   - passwordHash string
func (_e *UserRepositoryMock_Expecter) UpdatePassword(ctx interface{}, id interface{}, passwordHash interface{}) *UserRepositoryMock_UpdatePassword_Call {
	return &UserRepositoryMock_UpdatePassword_Call{Call: _e.mock.On("UpdatePassword", ctx, id, passwordHash)}
}

func (_c *UserRepositoryMock_UpdatePassword_Call) Run(run func(ctx context.Context, id domain.UserID, passwordHash string)) *UserRepositoryMock_UpdatePassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.UserID), args[2].(string))
	})
	return _c
}

func (_c *UserRepositoryMock_UpdatePassword_Call) Return(_a0 domain.User, _a1 bool, _a2 error) *UserRepositoryMock_UpdatePassword_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *UserRepositoryMock_UpdatePassword_Call) RunAndReturn(run func(context.Context, domain.UserID, string) (domain.User, bool, error)) *UserRepositoryMock_UpdatePassword_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRole provides a mock function with given fields: ctx, id, role
func (_m *UserRepositoryMock) UpdateRole(ctx context.Context, id domain.UserID, role domain.UserRole) (domain.User, bool, error) {
	ret := _m.Called(ctx, id, role)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRole")
	}

	var r0 domain.User
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.UserID, domain.UserRole) (domain.User, bool, error)); ok {
		return rf(ctx, id, role)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.UserID, domain.UserRole) domain.User); ok {
		r0 = rf(ctx, id, role)
	} else {
		r0 = ret.Get(0).(domain.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.UserID, domain.UserRole) bool); ok {
		r1 = rf(ctx, id, role)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, domain.UserID, domain.UserRole) error); ok {
		r2 = rf(ctx, id, role)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// UserRepositoryMock_UpdateRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRole'
type UserRepositoryMock_UpdateRole_Call struct {
	*mock.Call
}

// UpdateRole is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.UserID
//   - role domain.UserRole
func (_e *UserRepositoryMock_Expecter) UpdateRole(ctx interface{}, id interface{}, role interface{}) *UserRepositoryMock_UpdateRole_Call {
	return &UserRepositoryMock_UpdateRole_Call{Call: _e.mock.On("UpdateRole", ctx, id, role)}
}

func (_c *UserRepositoryMock_UpdateRole_Call) Run(run func(ctx context.Context, id domain.UserID, role domain.UserRole)) *UserRepositoryMock_UpdateRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.UserID), args[2].(domain.UserRole))
	})
	return _c
}

func (_c *UserRepositoryMock_UpdateRole_Call) Return(_a0 domain.User, _a1 bool, _a2 error) *UserRepositoryMock_UpdateRole_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *UserRepositoryMock_UpdateRole_Call) RunAndReturn(run func(context.Context, domain.UserID, domain.UserRole) (domain.User, bool, error)) *UserRepositoryMock_UpdateRole_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserRepositoryMock creates a new instance of UserRepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRepositoryMock {
	mock := &UserRepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
